export enum ORDER_STATUS {
  PENDING = 'PENDING',
  NEGOTIATING = 'NEGOTIATING',
  APPROVED = 'APPROVED',
  DECLINED = 'DECLINED',
}

export enum PAYMENT_STATUS {
  PENDING = 'PENDING',
  PAID = 'PAID',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
  FAILED = 'FAILED',
  COMPLETED = 'COMPLETED',
}
